//var translate =
module.exports = {
    you_result: {
        ru: "Ваш результат",
        en: "Your result",
        de: "Ihr Ergebnis",
        it: "Il tuo risultato",
        es: "Tu resultado",
        pt: "Seu resultado",
        fr: "Votre résultat",
        zh: "你的结果",
        ja: "あなたの結果",
        ko: "당신의 결과",
        pl: "Your result",
        tr: "Sizin sonuç"
    },
    max_speed: {
        ru: "Максимальная скорость",
        en: "Max speed",
        de: "Maximale Geschwindigkeit",
        it: "La velocità massima",
        es: "La velocidad máxima",
        pt: "A velocidade máxima",
        fr: "Vitesse maximale ",
        zh: "最大速度",
        ja: "最大速度",
        ko: "최대 속도",
        pl: "Max speed",
        tr: "Max hız"
    },
    pushToStart: {
        ru: "Нажмите чтобы начать",
        en: "Push to start",
        de: "Tippen Sie zum Anfangen",
        it: "Premi per iniziare",
        es: "Haz clic para iniciar",
        pt: "Clique para iniciar",
        fr: "Appuyez pour commencer",
        zh: "点击为了开始",
        ja: "スタートするために押してください",
        ko: "시작하려고 누르세요",
        pl: "Push to start",
        tr: "Başlamak için basın"
    },
    calibrationWarning: {
        ru: "Закрепите устройство и нажмите Продолжить для начала калибровки",
        en: "Fix the device and press Continue to start calibration",
        de: "Befestigen Sie das Gerät und drücken Sie Fortfahren, um Kalibrierung anzufangen",
        it: "Fissa il despositivo e premi \"Continuo\" per iniziare la taratura",
        es: "Asegura el dispositivo y haz clic en Continuar para iniciar la calibración",
        pt: "Assegure o seu dispositivo e clique em Continuar para iniciar a calibração",
        fr: "Fixez le dispositif et tapez \"Continuer\" pour commencer le calibrage",
        zh: "固定设备，然后点击\"继续\"为了开始校准",
        ja: "キャリブレーションをスタートさせるために装置をを固定して「続く」を押してください",
        ko: "장치를 고정하고 눈금을 매기기 시작하려고 계속을 누르세요",
        pl: "Fix the device and press Continue to start calibration",
        tr: "Aygıtı güven ve kalibrasyonu başlatmak için Devam Et tıklatın"
    },
    allEraseWarning: {
        ru: "Вы уверены, что хотите удалить все результаты?",
        en: "Are you sure you want to delete all results?",
        de: "Wollen Sie wirklich alle Resultate löschen?",
        it: "Davvero vorresti cancellare tutti i risultati?",
        es: "¿Seguro que quieres eliminar todos los resultados?",
        pt: "Tem certeza de que deseja excluir todos os resultados?",
        fr: "Êtes-vous sûr que vous voulez supprimer tous les résultats?",
        zh: "确定要删除所有的结果吗？",
        ja: "本当に全ての結果を削除しますか？",
        ko: "모든 결과를 삭제하시겠습니까?",
        pl: "Are you sure you want to delete all results?",
        tr: "Tüm sonuçları silmek istediğinizden emin misiniz?"
    },
    useGPS: {
        ru: "Использовать GPS",
        en: "Use GPS",
        de: "GPS verwenden",
        it: "Usare GPS",
        es: "Usar GPS",
        pt: "Usar GPS",
        fr: "Utiliser GPS",
        zh: "使用GPS",
        ja: "GPSを利用する",
        ko: "GPS 사용합니다",
        pl: "Use GPS",
        tr: "GPS kullan"
    },
    kilometers: {
        ru: "Километры",
        en: "Kilometers",
        de: "Kilometer",
        it: "Chilometri",
        es: "Kilómetros",
        pt: "Quilômetros",
        fr: "Kilomètres ",
        zh: "公里",
        ja: "キロ",
        ko: "킬로미터",
        pl: "Kilometers",
        tr: "Kilometre"
    },
    calibrationCompleted: {
        ru: "Калибровка завершена!",
        en: "Calibration is completed!",
        de: "Kalibrierung ist abgeschlossen!",
        it: "Taratura completata!",
        es: "¡La calibración se ha completada!",
        pt: "A calibração é completada!",
        fr: "Calibrage est accompli",
        zh: "校准完成！",
        ja: "キャリブレーションは完了です",
        ko: "교정이 완료되었습니다!",
        pl: "Calibration is completed!",
        tr: "Kalibrasyon tamamlandı!"
    },
    resultsNoData: {
        ru: "Нет данных",
        en: "No data",
        de: "Keine Daten",
        it: "Non ci sono i dati",
        es: "Sin información",
        pt: "Sem informação",
        fr: "Pas d'information",
        zh: "无数据",
        ja: "データがありません",
        ko: "데이터가 없습니다",
        pl: "No data",
        tr: "Bilgi yok"
    },
    optionDisabled: {
        ru: "Эту настройку нельзя изменить пока идет измерение",
        en: "You can't change this setting while measurement is being done",
        de: "Diese Einstellung kann während der Vermessung nicht verändert werden",
        it: "Non si può cambiare questa impostazione durante la misurazione.",
        es: "Este ajuste no se puede cambiar mientras que la medida está en el proceso",
        pt: "Esta definição não pode ser alterada enquanto a medida está no processo",
        fr: "Ce réglage est inaccessible pendant le mesurage",
        zh: "测量时不可以调整",
        ja: "測定中はこの設定が変えられません",
        ko: "측정하면서 설정을 변경할 수 없습니다",
        pl: "You can't change this setting while measurement is being done",
        tr: "Bir boyut varken bu ayar değiştirilemez"
    },
    /**
     * My translated
     **/
    settings: {
        ru: "Настройки",
        en: "Settings",
        de: "Einstellungen",
        it: "Impostazioni",
        es: "Ajustes",
        pt: "Opções",
        fr: "Réglages",
        zh: "设置",
        ja: "設定",
        ko: "설정",
        pl: "Narzędzia",
        tr: "Ayarlar"
    },
    distance: {
        ru: "Расстояние",
        en: "Distance",
        de: "Strecke",
        it: "Distanza",
        es: "Distancia",
        pt: "Distância",
        fr: "Distance",
        zh: "距离",
        ja: "距離",
        ko: "Distance",
        pl: "Distance",
        tr: "Mesafe"
    },
    km: {
        ru: "км",
        en: "km",
        de: "km",
        it: "km",
        es: "km",
        pt: "km",
        fr: "km",
        zh: "公里",
        ja: "km",
        ko: "km",
        pl: "km",
        tr: "km"
    },
    kmh: {
        ru: "км/ч",
        en: "km/h",
        de: "km/st",
        it: "km/h",
        es: "km/h",
        pt: "km/h",
        fr: "km/h",
        zh: "km/h",
        ja: "km/h",
        ko: "km/h",
        pl: "km/h",
        tr: "km/s"
    },
    mph: {
        ru: "м/ч",
        en: "m/h",
        de: "m/st",
        it: "m/h",
        es: "m/h",
        pt: "m/h",
        fr: "m/h",
        zh: "m/h",
        ja: "m/h",
        ko: "m/h",
        pl: "m/h",
        tr: "m/s"
    },

    mile: {
        ru: "м",
        en: "m",
        de: "m",
        it: "m",
        es: "m",
        pt: "m",
        fr: "m",
        zh: "m",
        ja: "m",
        ko: "m",
        pl: "m",
        tr: "m"
    },

    unitsOfMeasure: {
        ru: "Единицы измерения",
        en: "Units of measure",
        de: "Maßeinheit",
        it: "Unità di misura",
        es: "Unidades de medida",
        pt: "Unidades de medida",
        fr: "Unités de mesures",
        zh: "测量単位",
        ja: "測定の単位",
        ko: "측정단위",
        pl: "Units of measure",
        tr: "Birimler"
    },
    Calibrate: {
        ru: "Калибровать",
        en: "Calibrate",
        de: "Kalibrieren",
        it: "Imposta",
        es: "Сalibrar",
        pt: "Сalibrar",
        fr: "Calibrer ",
        zh: "校准",
        ja: "校正する",
        ko: "눈금을 매기기",
        pl: "Calibrate",
        tr: "Ayarla"
    },
    milles: {
        ru: "Мили",
        en: "Miles",
        de: "Meilen",
        it: "Miglia",
        es: "Millas",
        pt: "Milhas",
        fr: "Miles",
        zh: "英里",
        ja: "マイル",
        ko: "마일",
        pl: "Miles",
        tr: "Miller"
    },
    yes: {
        ru: "Да",
        en: "Yes",
        de: "Ja",
        it: "Sì",
        es: "Sí",
        pt: "Sim",
        fr: "Oui",
        zh: "确定",
        ja: "イェース",
        ko: "예",
        pl: "Tak",
        tr: "Evet"
    },
    cancel: {
        ru: "Отмена",
        en: "Cancel",
        de: "Abbrechen",
        it: "Cancella",
        es: "Cancelación",
        pt: "Cancelar",
        fr: "Annuler",
        zh: "取消",
        ja: "キャンセル",
        ko: "취소",
        pl: "Usunąć",
        tr: "İptal"
    },
    pleaseWait: {
        ru: "Пожалуйста, подождите",
        en: "Please, wait",
        de: "Bitte warten",
        it: "Si prega di aspettare",
        es: "Por favor, espera",
        pt: "Por favor, espere",
        fr: "Attendez, s'il vous plaît",
        zh: "请稍等",
        ja: "少々お待ちください",
        ko: "좀 기다려 주세요",
        pl: "Please, wait",
        tr: "Lütfen bekleyin"
    },
    Ok: {
        ru: "Ок",
        en: "Ok",
        de: "OK",
        it: "OK",
        es: "Ok",
        pt: "Ok",
        fr: "Ok",
        zh: "OK",
        ja: "OK",
        ko: "오케이 ",
        pl: "Ok",
        tr: "Ok"
    },
    continueInf: {
        ru: "Продолжить",
        en: "Continue",
        de: "Fortfahren",
        it: "Continuo",
        es: "Continuar",
        pt: "Continuar",
        fr: "Continuer",
        zh: "继续",
        ja: "続く",
        ko: "계속합니다",
        pl: "Continue",
        tr: "Devam et"
    },
    speed: {
        ru: "Скорость",
        en: "Speed",
        de: "Geschwindigkeit",
        it: "Velocità",
        es: "Velocidad",
        pt: "Velocidade",
        fr: "vitesse",
        zh: "速度",
        ja: "スピード",
        ko: "속도",
        pl: "Szybkość",
        tr: "Hız"
    },
    date: {
        ru: "Дата",
        en: "Date",
        de: "Datum",
        it: "Data",
        es: "Fecha",
        pt: "Data",
        fr: "date",
        zh: "日期",
        ja: "日付",
        ko: "날짜",
        pl: "Data",
        tr: "Tarih"
    },
    results: {
        ru: "Результаты",
        en: "Results",
        de: "Ergebnisse",
        it: "Risultati",
        es: "Resultados",
        pt: "Resultados",
        fr: "Résultats",
        zh: "结果",
        ja: "結果",
        ko: "결과",
        pl: "Wyniki",
        tr: "Sonuçlar"
    }
};
